version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_MCSP_Github_2207Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
